[build]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/*"
to = "https://movies-explorer-api-yv7u.onrender.com/:splat"
status = 200
